// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFXXGUo-N7VJr2riEY2OJiHz-I1hMRqKk',
    appId: '1:1074553929048:web:159717f716e610fab8b92d',
    messagingSenderId: '1074553929048',
    projectId: 'finalproject-46172',
    authDomain: 'finalproject-46172.firebaseapp.com',
    storageBucket: 'finalproject-46172.appspot.com',
    measurementId: 'G-442VDDPM7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBwqOf603GX1w-r0TaQIUKFpaJxEYWiM',
    appId: '1:1074553929048:android:8d50f7d2207ac8e5b8b92d',
    messagingSenderId: '1074553929048',
    projectId: 'finalproject-46172',
    storageBucket: 'finalproject-46172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASXbcf7zH7lJRHjNPZeuJ9hiJ3eAGxYZ8',
    appId: '1:1074553929048:ios:368870efc29794ceb8b92d',
    messagingSenderId: '1074553929048',
    projectId: 'finalproject-46172',
    storageBucket: 'finalproject-46172.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
